version: "3"
services:
  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/MicroservicesTestPrj
      - /MicroservicesTestPrj/products/node_modules
    env_file:
      - ./products/.env
  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    container_name: gateway
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/MicroservicesTestPrj
      - /MicroservicesTestPrj/gateway/node_modules
    env_file:
      - ./gateway/.env
